
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     public/common/top_controls_state.h

package org.chromium.content_public.common;import org.chromium.content_shell_apk.R;

public class TopControlsState {
  public static final int SHOWN = 1;
  public static final int HIDDEN = 2;
  public static final int BOTH = 3;
}
