
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     selection_event_type.h

package org.chromium.ui.touch_selection;import org.chromium.content_shell_apk.R;

public class SelectionEventType {
  public static final int SELECTION_SHOWN = 0;
  public static final int SELECTION_CLEARED = 1;
  public static final int SELECTION_DRAG_STARTED = 2;
  public static final int SELECTION_DRAG_STOPPED = 3;
  public static final int INSERTION_SHOWN = 4;
  public static final int INSERTION_MOVED = 5;
  public static final int INSERTION_TAPPED = 6;
  public static final int INSERTION_CLEARED = 7;
  public static final int INSERTION_DRAG_STARTED = 8;
}
